KERMESSE_MYGRO/Models/tbl_moneda.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KERMESSE_MYGRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_moneda()
        {
            this.tbl_arqueocaja_det = new HashSet<tbl_arqueocaja_det>();
            this.tbl_denominacion = new HashSet<tbl_denominacion>();
            this.tbl_tasacambio = new HashSet<tbl_tasacambio>();
            this.tbl_tasacambio1 = new HashSet<tbl_tasacambio>();
        }
    
        public int id_moneda { get; set; }
        public string nombre { get; set; }
        public string signo { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_arqueocaja_det> tbl_arqueocaja_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_denominacion> tbl_denominacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tasacambio> tbl_tasacambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tasacambio> tbl_tasacambio1 { get; set; }
    }
}

KERMESSE_MYGRO/Controllers/Tbl_MonedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KERMESSE_MYGRO.Models;

namespace KermesseApp.Controllers
{
    public class Tbl_MonedaController : Controller
    {
        private KERMESSEEntities db = new KERMESSEEntities();
        // GET: Tbl_moneda
        public ActionResult Tbl_Moneda()
        {
            return View(db.tbl_moneda.ToList());
        }

        public ActionResult InsertMoneda()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InsertMoneda(tbl_moneda tm)
        {
            if (ModelState.IsValid)
            {
                tbl_moneda tbm = new tbl_moneda();
                tbm.nombre = tm.nombre;
                tbm.signo = tm.signo;
                tbm.estado = 1;

                db.tbl_moneda.Add(tbm);
                db.SaveChanges();
            }

            ModelState.Clear();

            var list = db.tbl_moneda.ToList();

            return View("Tbl_moneda", list);
        }

        public ActionResult DeleteMoneda(int id)
        {
            tbl_moneda tbm = new tbl_moneda();
            tbm = db.tbl_moneda.Find(id);
            db.tbl_moneda.Remove(tbm);
            db.SaveChanges();

            var list = db.tbl_moneda.ToList();

            return View("Tbl_moneda", list);
        }

    }
}

KERMESSE_MYGRO/Views/Tbl_Moneda/InsertMoneda.cshtml
@using KERMESSE_MYGRO.Models;

@{
    /*Instanciamos objetos y variables */
    KERMESSEEntities db = new KERMESSEEntities();
    tbl_usuario tu = new tbl_usuario();
    tbl_rol_usuario tru = new tbl_rol_usuario();
    List<vw_rol_opciones> listopc = new List<vw_rol_opciones>();
    Int32 idRol = 0;
    String opcion = "";
    Int32 longitud = 0;
    Boolean acceso = false;

    /* Obtenemos la sesion */
    tu = Session["usuario"] as tbl_usuario;

    /* Obtenemos el rol del usuario*/
    tru = db.tbl_rol_usuario.Where(x => x.id_usuario.Equals(tu.id_usuario)).FirstOrDefault();
    idRol = tru.id_rol;
    /* Obtenemos la lista de opciones del rol*/
    listopc = db.vw_rol_opciones.Where(x => x.id_rol.Equals(idRol)).ToList();

    string url = HttpContext.Current.Request.Url.AbsoluteUri;
    string[] separado = url.Split('/');
    string opcionActual = separado[separado.Length - 1];

    longitud = listopc.Count();//Obtenemos la cantidad de elementos
    for (int i = 0; i < longitud; i++)
    {
        //obtenemos la columna opcion de la matriz y/o lista de elementos
        opcion = listopc[i].opcion;
        if (opcionActual.Equals(opcion)) //COMPARAMOS LA OPCION ACTUAL CON CADA OPCIÓN DE LA MATRIZ
        {
            acceso = true; //ACCESO CONCEDIDO
            break;
        }
    }
    if (!acceso)
    {
        Response.Redirect("~/Home/Error");
    }


}



@model KERMESSE_MYGRO.Models.tbl_moneda

@{
    ViewBag.Title = "InsertMoneda";
}


<div class="container-fluid">
    <h1 class="mt-4">Gestión de Moneda</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="" @Url.Action("Index", "Home") ">Inicio</a></li>
        <li class="breadcrumb-item "><a href="@Url.Action("tbl_moneda", "Tbl_Moneda")">Gestión de Moneda</a></li>
        <li class="breadcrumb-item active">Registrar una Moneda</li>
    </ol>
    <div class="card mb-4">
        <img src="https://miviajeanewyork.files.wordpress.com/2016/02/monedas-banner.jpg?w=1390" class="card-img-top" alt="moneda">

        <div class="card-body">

            <div class="table">

                <h2>Registrando una nueva moneda</h2>

                <div style="text-align: right;">
                    <a href="@Url.Action("tbl_moneda", "Tbl_Moneda")" title="Regresar a la página anterior">
                        <i class="fas fa-arrow-circle-left"></i>
                        Regresar a la página anterior
                    </a><br><br>
                </div>

                @using (Html.BeginForm("InsertMoneda", "Tbl_Moneda", FormMethod.Post))
                {

                    <div class="form-row">
                        <div class="col-md-12">

                            <div class="row">

                                <div class="col">
                                    <label class="small mb-1">Nombre de la Moneda: </label>
                                    @Html.ValidationMessageFor(x => x.nombre, "", new { @class = "text-danger" })
                                    @Html.TextBoxFor(x => x.nombre, new { @class = "form-control" })
                                </div>

                                <div class="col">
                                    <label class="small mb-1">Simbolo de la Moneda: </label>
                                    @Html.ValidationMessageFor(x => x.signo, "", new { @class = "text-danger" })
                                    @Html.TextBoxFor(x => x.signo, new { @class = "form-control" })
                                </div>

                            </div>

                            <br>

                            <div class="row form-row" style="text-align: center;">

                                <div class="col">
                                    <input class="btn btn-primary btn-block col-md-12" type="submit" value="Registrar nueva moneda" />
                                </div>

                                <div class="col">
                                    <input class="btn btn-outline-danger btn-block col-md-12" type="reset" value="Cancelar" />
                                </div>

                            </div>

                            <br>

                        </div>
                    </div>

                }

            </div>
        </div>
    </div>
</div>

KERMESSE_MYGRO/Views/Tbl_Moneda/Tbl_Moneda.cshtml
@using KERMESSE_MYGRO.Models;

@{
    /*Instanciamos objetos y variables */
    KERMESSEEntities db = new KERMESSEEntities();
    tbl_usuario tu = new tbl_usuario();
    tbl_rol_usuario tru = new tbl_rol_usuario();
    List<vw_rol_opciones> listopc = new List<vw_rol_opciones>();
    Int32 idRol = 0;
    String opcion = "";
    Int32 longitud = 0;
    Boolean acceso = false;

    /* Obtenemos la sesion */
    tu = Session["usuario"] as tbl_usuario;

    /* Obtenemos el rol del usuario*/
    tru = db.tbl_rol_usuario.Where(x => x.id_usuario.Equals(tu.id_usuario)).FirstOrDefault();
    idRol = tru.id_rol;
    /* Obtenemos la lista de opciones del rol*/
    listopc = db.vw_rol_opciones.Where(x => x.id_rol.Equals(idRol)).ToList();

    string url = HttpContext.Current.Request.Url.AbsoluteUri;
    string[] separado = url.Split('/');
    string opcionActual = separado[separado.Length - 1];

    longitud = listopc.Count();//Obtenemos la cantidad de elementos
    for (int i = 0; i < longitud; i++)
    {
        //obtenemos la columna opcion de la matriz y/o lista de elementos
        opcion = listopc[i].opcion;
        if (opcionActual.Equals(opcion)) //COMPARAMOS LA OPCION ACTUAL CON CADA OPCIÓN DE LA MATRIZ
        {
            acceso = true; //ACCESO CONCEDIDO
            break;
        }
    }
    if (!acceso)
    {
        Response.Redirect("~/Home/Error");
    }


}


@model IEnumerable<KERMESSE_MYGRO.Models.tbl_moneda>

@{
    ViewBag.Title = "Tbl_Moneda";
}



<div class="container-fluid">
    <h1 class="mt-4">Gestión de Monedas</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Inicio</a></li>
        <li class="breadcrumb-item active">Gestión de Moneda</li>
    </ol>
    <div class="card mb-4">
        <img src="https://miviajeanewyork.files.wordpress.com/2016/02/monedas-banner.jpg?w=1390" class="card-img-top" alt="moneda">

        <div class="card-body">

            <div class="table-responsive">

                <h2>Registro de Monedas</h2>

                <div class="row p-4 no-gutters justify-content-between align-items-center">
                    
                    <div class="col-12 col-md-4">

                        <div style="text-align: right;">

                            <a href="@Url.Action("InsertMoneda")">
                                <button type="button" class="btn btn-outline-primary btn-md">
                                    <i class="fas fa-plus"></i> &nbsp;Agregar nueva moneda
                                </button>
                            </a>

                        </div>
                    </div>
                </div>

                <table class="table table-bordered table-hover" id="tbl" width="100%" style="text-align: center;" cellspacing="0">

                    <thead class="table-dark">
                        <tr>
                            <th>Nombre</th>
                            <th>Simbolo</th>
                            <th width="20%">Opciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.signo)
                                </td>
                                <td>
                                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                                    <a href="#"
                                       title="Modificar los datos de la moneda">
                                        <i class="fas fa-pencil-alt"></i>
                                        Editar
                                    </a>

                                    &nbsp;&nbsp;

                                    <a href="@Url.Action("DeleteMoneda", new { id=item.id_moneda})"
                                       title="Eliminar Moneda">
                                        <i class="fas fa-trash-alt"></i>
                                        Eliminar
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                    <tfoot class="table-dark">
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tfoot>

                </table>
            </div>
        </div>
    </div>
</div>